version: '3.4'

volumes:
  lighthouse_data:
  prysm_data:
  lodestar_data:
  teku_data:

x-geth: &geth
  build:
    context: ./geth
    dockerfile: Dockerfile.geth
  depends_on:
    genesis-generator:
      condition: service_completed_successfully
  entrypoint: geth.sh
  healthcheck:
    test: ["CMD", "curl", "--fail", "localhost:8545"]
    interval: 2s
    timeout: 2s
    retries: 40
    start_period: 1s
  volumes:
    - './config_data:/config_data'
    - type: bind
      source: ./geth/geth.sh
      target: /usr/local/bin/geth.sh


x-lighthouse-beacon-node: &lighthouse-bn
  build:
    context: ./lighthouse
    dockerfile: Dockerfile.lighthouse
  entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_1", "http://geth-1:8551"]
  environment:
    - P2P_PORT=9000
  ports:
    - "5052:5052"
    - "8000:8000"
    - "9000:9000"
  volumes:
    - ./lighthouse_data:/data
    - ./config_data:/config_data
    - type: bind
      source: ./lighthouse/run_beacon_node.sh
      target: /usr/local/bin/run_beacon_node.sh
    - type: bind
      source: ./shared/trusted_setup.txt
      target: /config/trusted_setup.txt
    - type: bind
      source: ./shared/jwtsecret
      target: /config/jwtsecret


services:
  genesis-generator:
    # image: fab10/ethereum-genesis-generator:eip4844
    build:
      context: ./ethereum-genesis-generator
      dockerfile: Dockerfile
    entrypoint: run_genesis_generator.sh
    volumes:
      - ./shared/run_genesis_generator.sh:/usr/local/bin/run_genesis_generator.sh
      - ./shared/genesis-generator-configs:/config
      - ./shared/generated-configs:/gen-configs
      - ./lighthouse_data:/lighthouse_data
      - ./config_data:/data

  geth-1:
    <<: *geth
    ports:
      - '8545:8545'
      - '8551:8551'
    volumes:
      - './data/geth-1:/db'
      - './config_data:/config_data'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh

  geth-2:
    <<: *geth
    ports:
      - '8546:8545'
      - '8552:8551'
    volumes:
      - './data/geth-2:/db'
      - './config_data:/config_data'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh


  # TODO: move bootnode to genesis-generator
  bootnode:
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    pull_policy: never
    command: run_bootnode.sh
    volumes:
      - ./lighthouse_data:/data
      - ./config_data:/config_data
      - ./shared/genesis-generator-configs:/config
      - type: bind
        source: ./lighthouse/run_bootnode.sh
        target: /usr/local/bin/run_bootnode.sh

  prysm-beacon-node:
    <<: *prysm-bn
    depends_on:
      geth-1:
        condition: service_started
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    environment:
      <<: *prysm-bn-env
      EXECUTION_NODE_URL: http://geth-1:8551
      PROCESS_NAME: beacon-node
      MIN_SYNC_PEERS: 0
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'

  prysm-beacon-node-besu-el:
    <<: *prysm-bn
    depends_on:
      besu-1:
        condition: service_started
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    environment:
      <<: *prysm-bn-env
      EXECUTION_NODE_URL: http://besu-1:8551
      PROCESS_NAME: beacon-node
      MIN_SYNC_PEERS: 0
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'

  prysm-beacon-node-follower:
    <<: *prysm-bn
    depends_on:
      geth-2:
        condition: service_started
      bootnode:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    environment:
      <<: *prysm-bn-env
      EXECUTION_NODE_URL: http://geth-2:8551
      PROCESS_NAME: beacon-node-follower
      P2P_TCP_PORT: 13001
      MIN_SYNC_PEERS: 1
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13001'

  prysm-validator-node:
    depends_on:
      prysm-beacon-node:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --force-clear-db
      --chain-config-file=/config_data/custom_config_data/config.yaml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --wallet-password-file=/prysm_data/wallet_pass.txt
      --wallet-dir=/prysm_data/wallet
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
      --verbosity trace
    ports:
      - '7500:7500'
    volumes:
      - './config_data:/config_data'
      - 'prysm_data:/prysm_data'

  prysm-validator-node-besu-el:
    depends_on:
      prysm-beacon-node-besu-el:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node-besu-el:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --force-clear-db
      --chain-config-file=/config_data/custom_config_data/config.yaml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --wallet-password-file=/prysm_data/wallet_pass.txt
      --wallet-dir=/prysm_data/wallet
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
      --verbosity trace
    ports:
      - '7500:7500'
    volumes:
      - './config_data:/config_data'
      - 'prysm_data:/prysm_data'


  lighthouse-beacon-node:
    <<: *lighthouse-bn
    depends_on:
      bootnode:
        condition: service_started
      geth-1:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_1", "http://geth-1:8551"]
    environment:
      - P2P_PORT=9000
    ports:
      - "5052:5052"
      - "8000:8000"
      - "9000:9000"

  lighthouse-beacon-node-follower:
    <<: *lighthouse-bn
    depends_on:
      bootnode:
        condition: service_started
      geth-2:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    entrypoint: ["run_beacon_node.sh", "-d", "debug", "/data/node_2", "http://geth-2:8551"]
    environment:
      - P2P_PORT=9001
    ports:
      - "5053:5052"
      - "8001:8000"
      - "9001:9001"

  lighthouse-validator-node:
    depends_on:
      lighthouse-beacon-node:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    command: >
      lighthouse
      --debug-level info
      vc
      --validators-dir /data/validators
      --secrets-dir /data/secrets
      --testnet-dir /config_data/custom_config_data
      --init-slashing-protection
      --beacon-nodes http://lighthouse-beacon-node:8000
      --suggested-fee-recipient 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    volumes:
      - ./lighthouse_data:/data
      - ./config_data:/config_data

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
